"""D047 — Legacy memory contamination cleanup (post-D046 migration)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from acm import CognitiveEngine
from acm.provenance import (
    TRUSTED_USER_STATEMENT,
    TRUSTED_USER_TEACHING,
    HostOperation,
    IngestionActor,
    IngestionProvenance,
    MessageRole,
    classify_untrusted_artifact,
    cleanup_legacy_contamination,
)

# Genuine pre-D046 snapshot generated by ACM v0.18.4 (commit 3023ed8) — four
# legitimate user memories plus five untrusted artifacts the old encode
# boundary accepted (tool, diagnostic, reflection, system, infrastructure).
FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "pre_d046_contaminated_snapshot.json"

ARTIFACT_PROBES = (
    "tool memory_search",
    "probe-yellow",
    "reflection trace",
    "session initialized",
    "memory backend timeout",
)


def _import_legacy_graph() -> CognitiveEngine:
    engine = CognitiveEngine(agent_id="aria")
    engine.import_snapshot(str(FIXTURE))
    return engine


def _store_blob(engine: CognitiveEngine) -> str:
    return json.dumps(
        {
            "experiences": [e.summary for e in engine.store.experiences.values()],
            "metadata": [e.meta_dict() for e in engine.store.experiences.values()],
            "concepts": [c.to_public() for c in engine.store.concepts.values()],
            "provenance": [p.to_public() for p in engine.store.provenance.values()],
        },
        sort_keys=True,
    ).lower()


def test_d047_legacy_contamination_is_recalled_before_migration() -> None:
    """Confirms the investigation: pre-D046 artifacts recall despite D046."""
    engine = _import_legacy_graph()
    result = engine.cognitive_respond("What is my favorite color?")
    assert result["status"] == "known"
    assert "probe-yellow" in (result["memory"] or "")


def test_d047_no_current_encode_path_bypasses_the_trust_gate() -> None:
    """Live-bypass check: encode/revise/reflect_on all reject untrusted input."""
    engine = _import_legacy_graph()
    exp_id = next(iter(engine.store.experiences))
    payload = "Tool memory_search worked for: bypass probe."
    assert engine.encode(payload)["reason"] == "memory_trust"
    assert engine.revise_experience(exp_id, payload)["reason"] == "memory_trust"
    assert engine.reflect_on(exp_id, payload)["reason"] == "memory_trust"


def test_d047_migration_removes_only_contaminated_memories() -> None:
    engine = _import_legacy_graph()
    report = cleanup_legacy_contamination(engine)

    assert report["clean"] is False
    assert report["removed_experiences"] == 5
    reasons = set(report["reasons"].values())
    assert reasons == {
        "legacy_untrusted_artifact:tool_output",
        "legacy_untrusted_artifact:diagnostic_output",
        "legacy_untrusted_artifact:reflection_output",
        "legacy_untrusted_artifact:system_message",
        "legacy_untrusted_artifact:infrastructure_log",
    }

    blob = _store_blob(engine)
    for probe in ARTIFACT_PROBES:
        assert probe not in blob

    # Legitimate user memories are preserved.
    summaries = " | ".join(e.summary.lower() for e in engine.store.experiences.values())
    assert "jeff" in summaries
    assert "blue" in summaries
    assert "sarah" in summaries
    assert "science museum" in summaries


def test_d047_contaminated_preference_restored_to_taught_value() -> None:
    """The diagnostic artifact superseded blue pre-D046; cleanup restores blue."""
    engine = _import_legacy_graph()
    cleanup_legacy_contamination(engine)

    result = engine.cognitive_respond("What is my favorite color?")
    assert result["status"] == "known"
    assert result["memory"] == "Your favorite color is blue."
    assert result["uncertainty"] is None

    values = {
        a.value: a.active
        for c in engine.store.concepts.values()
        for a in c.attributes
        if a.key == "favorite_color"
    }
    assert values == {"blue": True}


def test_d047_identity_preserved_identically() -> None:
    control = _import_legacy_graph()
    cleaned = _import_legacy_graph()
    cleanup_legacy_contamination(cleaned)

    def _user_name(engine: CognitiveEngine) -> list[tuple[str, str, bool]]:
        return sorted(
            (a.key, a.value, a.active)
            for c in engine.store.concepts.values()
            if c.identity
            for a in c.attributes
            if a.key == "name"
        )

    assert _user_name(cleaned) == _user_name(control)
    assert ("name", "Jeff", True) in _user_name(cleaned)


def test_d047_valid_provenance_preserved() -> None:
    engine = _import_legacy_graph()
    before_valid = {
        pid
        for pid, rec in engine.store.provenance.items()
        if not any(
            p
            in (
                engine.store.experiences.get(rec.artifact_id).summary.lower()
                if rec.artifact_id in engine.store.experiences
                else ""
            )
            for p in ARTIFACT_PROBES
        )
    }
    cleanup_legacy_contamination(engine)
    # Every remaining provenance record points at a surviving artifact.
    surviving = set(engine.store.experiences) | set(engine.store.concepts)
    for rec in engine.store.provenance.values():
        assert rec.artifact_id in surviving
    assert set(engine.store.provenance) <= before_valid


def test_d047_migration_is_idempotent() -> None:
    engine = _import_legacy_graph()
    first = cleanup_legacy_contamination(engine)
    assert first["removed_experiences"] == 5

    checksum_after_first = engine.verify_persistence()["checksum"]
    second = cleanup_legacy_contamination(engine)
    assert second["clean"] is True
    assert second["removed_experiences"] == 0
    assert second["removed_concepts"] == 0
    assert second["removed_attributes"] == 0
    assert second["removed_associations"] == 0
    assert second["removed_provenance"] == 0
    assert engine.verify_persistence()["checksum"] == checksum_after_first


def test_d047_clean_graph_untouched() -> None:
    engine = CognitiveEngine(agent_id="aria")
    engine.encode("My name is Jeff.", kind="identity", provenance=TRUSTED_USER_STATEMENT)
    engine.encode("My favorite color is blue.", kind="preference", provenance=TRUSTED_USER_TEACHING)
    checksum_before = engine.verify_persistence()["checksum"]
    report = cleanup_legacy_contamination(engine)
    assert report["clean"] is True
    assert report["removed_experiences"] == 0
    assert engine.verify_persistence()["checksum"] == checksum_before


def test_d047_teach_after_cleanup_and_injection_cannot_recontaminate() -> None:
    engine = _import_legacy_graph()
    cleanup_legacy_contamination(engine)

    taught = engine.encode(
        "My favorite color is blue.",
        kind="preference",
        provenance=TRUSTED_USER_TEACHING,
    )
    assert taught["encoded"] is True

    tool = IngestionProvenance(
        actor=IngestionActor.TOOL,
        host_operation=HostOperation.MEMORY_SEARCH,
        message_role=MessageRole.TOOL_RESULT,
    )
    for _ in range(10):
        rejected = engine.encode(
            "Tool memory_search worked for: Show the evidence for my favorite color.",
            provenance=tool,
        )
        assert rejected["encoded"] is False
        assert rejected["reason"] == "memory_trust"

    result = engine.cognitive_respond("What is my favorite color?")
    assert result["status"] == "known"
    assert result["memory"] == "Your favorite color is blue."

    # And a fresh cleanup pass still finds nothing to remove.
    assert cleanup_legacy_contamination(engine)["clean"] is True


def test_d047_d046_gate_still_rejects_missing_and_unknown_provenance() -> None:
    engine = _import_legacy_graph()
    cleanup_legacy_contamination(engine)
    assert engine.encode("My favorite color is green.")["detail"] == "missing_provenance"
    unknown = engine.encode(
        "My favorite color is green.",
        provenance=IngestionProvenance(
            actor=IngestionActor.UNKNOWN,
            host_operation=HostOperation.UNKNOWN,
            message_role=MessageRole.UNKNOWN,
        ),
    )
    assert unknown["reason"] == "memory_trust"


def test_d047_recorded_ineligible_source_removed_fail_closed() -> None:
    """Imported snapshots with fabricated D046 metadata are still removed."""
    from dataclasses import replace

    engine = CognitiveEngine(agent_id="aria")
    ok = engine.encode(
        "My favorite color is blue.", kind="preference", provenance=TRUSTED_USER_TEACHING
    )
    exp = engine.store.experiences[ok["experience_id"]]
    fabricated = dict(exp.metadata)
    fabricated["source_actor"] = "tool"
    fabricated["source_host_operation"] = "tool_execution"
    fabricated["source_message_role"] = "tool_result"
    engine.store.experiences[exp.id] = replace(exp, metadata=tuple(sorted(fabricated.items())))

    report = cleanup_legacy_contamination(engine)
    assert report["removed_experiences"] == 1
    assert report["reasons"][exp.id] == ("recorded_source_ineligible:actor_not_autobiographical")
    assert exp.id not in engine.store.experiences


def test_d047_internal_cognition_never_removed() -> None:
    engine = CognitiveEngine(agent_id="aria")
    engine.encode("My favorite color is blue.", kind="preference", provenance=TRUSTED_USER_TEACHING)
    goal_id = engine.open_goal("Finish the museum project", importance=0.7)
    engine.complete_goal(goal_id)
    engine.what_do_i_think("favorite color")  # Reflection organ birth

    internal = [
        e for e in engine.store.experiences.values() if "semantic_extraction" not in e.meta_dict()
    ]
    assert internal, "expected internal cognition experiences"
    report = cleanup_legacy_contamination(engine)
    assert report["clean"] is True
    for exp in internal:
        assert exp.id in engine.store.experiences


def test_d047_cleanup_flushes_durable_store(tmp_path: Path) -> None:
    path = tmp_path / "cleanup.db"
    engine = CognitiveEngine(agent_id="aria", persist_path=str(path), auto_persist=True)
    engine.import_snapshot(str(FIXTURE))
    report = engine.cleanup_legacy_contamination()
    assert report["removed_experiences"] == 5
    assert report["flushed"] is True

    restarted = CognitiveEngine(agent_id="aria", persist_path=str(path), auto_persist=True)
    blob = _store_blob(restarted)
    for probe in ARTIFACT_PROBES:
        assert probe not in blob
    result = restarted.cognitive_respond("What is my favorite color?")
    assert result["memory"] == "Your favorite color is blue."


@pytest.mark.parametrize(
    "text",
    (
        "My favorite color is blue.",
        "My name is Jeff.",
        "I visited the science museum with my son today.",
        "I prefer my coffee tools organized by size.",
        "My wife's name is Sarah.",
    ),
)
def test_d047_classifier_never_matches_legitimate_user_knowledge(text: str) -> None:
    assert classify_untrusted_artifact(text) is None


@pytest.mark.parametrize(
    ("text", "expected"),
    (
        ("Tool memory_search worked for: query.", "tool_output"),
        ("tool output: 3 rows", "tool_output"),
        ("memory_search result: none", "memory_search_output"),
        ("Search results: 0 hits", "memory_search_output"),
        ("Diagnostic: subsystem nominal", "diagnostic_output"),
        ("Reflection trace: user may prefer dark mode", "reflection_output"),
        ("[system] profile sync complete", "system_message"),
        ("System: session initialized", "system_message"),
        ("System prompt: You are a helpful assistant", "prompt_fragment"),
        ("ERROR: backend timeout", "infrastructure_log"),
        ("2026-07-17 12:00:00 worker started", "infrastructure_log"),
        ('{"key": "value"}', "implementation_metadata"),
        ("Metadata: schema_version=7", "implementation_metadata"),
    ),
)
def test_d047_classifier_matches_artifacts(text: str, expected: str) -> None:
    assert classify_untrusted_artifact(text) == expected
